### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Junqiao77** [ydchen0806/24ICM_E_O_Award_Paper_code#1]
可以麻烦作者上传一下你们实现的数据集吗？我们最近有老师布置相关任务，但我们在数据集的寻找上面遇到了困难，希望作者可以帮助一下

**Comment by ydchen0806** [comment]
可以的，但是这个比赛比较早，我忘记当时用的哪些数据了，我现在统一传到/data路径下，你可以参考使用

**Comment by ydchen0806** [comment]
有的数据集比较大，github传不上去，你留个邮箱我发你？

**Comment by Junqiao77** [comment]
好的，非常感谢！fujunqiao32@gmail.com
